/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Ride } from "./Ride";
import { RideCountArgs } from "./RideCountArgs";
import { RideFindManyArgs } from "./RideFindManyArgs";
import { RideFindUniqueArgs } from "./RideFindUniqueArgs";
import { CreateRideArgs } from "./CreateRideArgs";
import { UpdateRideArgs } from "./UpdateRideArgs";
import { DeleteRideArgs } from "./DeleteRideArgs";
import { PaymentFindManyArgs } from "../../payment/base/PaymentFindManyArgs";
import { Payment } from "../../payment/base/Payment";
import { User } from "../../user/base/User";
import { RideService } from "../ride.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Ride)
export class RideResolverBase {
  constructor(
    protected readonly service: RideService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "read",
    possession: "any",
  })
  async _ridesMeta(
    @graphql.Args() args: RideCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Ride])
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "read",
    possession: "any",
  })
  async rides(@graphql.Args() args: RideFindManyArgs): Promise<Ride[]> {
    return this.service.rides(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Ride, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "read",
    possession: "own",
  })
  async ride(@graphql.Args() args: RideFindUniqueArgs): Promise<Ride | null> {
    const result = await this.service.ride(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Ride)
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "create",
    possession: "any",
  })
  async createRide(@graphql.Args() args: CreateRideArgs): Promise<Ride> {
    return await this.service.createRide({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Ride)
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "update",
    possession: "any",
  })
  async updateRide(@graphql.Args() args: UpdateRideArgs): Promise<Ride | null> {
    try {
      return await this.service.updateRide({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Ride)
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "delete",
    possession: "any",
  })
  async deleteRide(@graphql.Args() args: DeleteRideArgs): Promise<Ride | null> {
    try {
      return await this.service.deleteRide(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Payment], { name: "payments" })
  @nestAccessControl.UseRoles({
    resource: "Payment",
    action: "read",
    possession: "any",
  })
  async findPayments(
    @graphql.Parent() parent: Ride,
    @graphql.Args() args: PaymentFindManyArgs
  ): Promise<Payment[]> {
    const results = await this.service.findPayments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Ride): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
